---
    - name: Install git
      yum:
        name: "git"
        state: present
        update_cache: yes
      become: true
    - name: clone from git
      ansible.builtin.git:
        repo: https://github.com/VKCOM/lighthouse.git
        dest: "{{ document_root }}"
        single_branch: yes
        version: master
      become: true
    - name: Copy lighthouse config
      become: true
      template:
        src: lighthouse.conf.j2
        dest: /etc/nginx/conf.d/lighthouse.conf
      notify: Restart Nginx