---
# tasks file for nginx-role
    - name: Install epel-release
      yum:
        name: epel-release
        state: latest
      become: true
    - name: install Nginx
      yum:
        name: nginx
        state: latest
        update_cache: yes
      become: true
      notify: Start Nginx
    - name: Copy nginx config
      become: true
      template:
        src: nginx.conf.j2
        dest: '{{ websrvconf }}'
        mode: 0755
      notify: Reload Nginx